import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Le CSS global
import ServiceWorkerManager from "../components/ServiceWorkerManager";

const geistSans = Geist({
  variable: "--background",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--foreground",
  subsets: ["latin"],
});

// Métadonnées pour la PWA
export const metadata: Metadata = {
  title: "Next.js PWA",
  description: "Une Progressive Web App construite avec Next.js",
  themeColor: "#000000",
  manifest: "/manifest.json",
  icons: {
    icon: "/favicon.ico",
    apple: "/icons/icon-192x192.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Gestionnaire de Service Worker */}
        <ServiceWorkerManager />
        {children}
      </body>
    </html>
  );
}







// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // Metadata pour la configuration PWA
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   themeColor: "#000000", // Couleur de la barre d'état/navigateur
//   manifest: "/manifest.json", // Lien vers le manifeste
//   icons: {
//     icon: "/favicon.ico", // Icône de l'application
//     apple: "/icons/icon-192x192.png", // Icône pour appareils iOS
//   },
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         {/* Ajout des meta-tags supplémentaires */}
//         <meta name="theme-color" content="#000000" />
//         <meta name="apple-mobile-web-app-capable" content="yes" />
//         <meta name="apple-mobile-web-app-status-bar-style" content="default" />
//         <link rel="manifest" href="/manifest.json" />
//         <link rel="icon" href="/favicon.ico" />
//         <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }





// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
